namespace TileMatch.Scripts.Gameplay.Tile
{
    public enum TileType
    {
        BluePentagon,
        BlueSquare,
        BlueStar,
        BrownPentagon,
        BrownSquare,
        BrownStar,
        CreamPentagon,
        CreamSquare,
        CreamStar,
        GreenPentagon,
        GreenSquare,
        GreenStar,
        LightBluePentagon,
        LightBlueSquare,
        LightBlueStar,
        OrangePentagon,
        OrangeSquare,
        OrangeStar,
        PinkPentagon,
        PinkSquare,
        PinkStar,
        PurplePentagon,
        PurpleSquare,
        PurpleStar,
        RedPentagon,
        RedSquare,
        RedStar,
        YellowPentagon,
        YellowSquare,
        YellowStar
    }
}